# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groundControl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groundControl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13groundControl.proto\"\x18\n\nmapRequest\x12\n\n\x02id\x18\x01 \x02(\t\"\'\n\x08mapReply\x12\x0b\n\x03map\x18\x01 \x02(\t\x12\x0e\n\x06\x62ounds\x18\x02 \x02(\t\"\x16\n\x06\x63mdReq\x12\x0c\n\x04size\x18\x01 \x02(\x05\"\x1c\n\x08\x63mdReply\x12\x10\n\x08\x63ommands\x18\x01 \x02(\t\"7\n\rserialRequest\x12\x0c\n\x04posX\x18\x01 \x02(\x05\x12\x0c\n\x04posY\x18\x02 \x02(\x05\x12\n\n\x02id\x18\x03 \x02(\x05\"!\n\x0bserialReply\x12\x12\n\nmineSerial\x18\x01 \x02(\t2\x86\x01\n\x0eground_control\x12\"\n\x06getMap\x12\x0b.mapRequest\x1a\t.mapReply\"\x00\x12#\n\x0bgetCommands\x12\x07.cmdReq\x1a\t.cmdReply\"\x00\x12+\n\tgetSerial\x12\x0e.serialRequest\x1a\x0c.serialReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groundControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=23
  _globals['_MAPREQUEST']._serialized_end=47
  _globals['_MAPREPLY']._serialized_start=49
  _globals['_MAPREPLY']._serialized_end=88
  _globals['_CMDREQ']._serialized_start=90
  _globals['_CMDREQ']._serialized_end=112
  _globals['_CMDREPLY']._serialized_start=114
  _globals['_CMDREPLY']._serialized_end=142
  _globals['_SERIALREQUEST']._serialized_start=144
  _globals['_SERIALREQUEST']._serialized_end=199
  _globals['_SERIALREPLY']._serialized_start=201
  _globals['_SERIALREPLY']._serialized_end=234
  _globals['_GROUND_CONTROL']._serialized_start=237
  _globals['_GROUND_CONTROL']._serialized_end=371
# @@protoc_insertion_point(module_scope)
