# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import groundControl_pb2 as groundControl__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in groundControl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ground_controlStub(object):
    """Ground Control service for rovers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMap = channel.unary_unary(
                '/ground_control/getMap',
                request_serializer=groundControl__pb2.mapRequest.SerializeToString,
                response_deserializer=groundControl__pb2.mapReply.FromString,
                _registered_method=True)
        self.getCommands = channel.unary_unary(
                '/ground_control/getCommands',
                request_serializer=groundControl__pb2.cmdReq.SerializeToString,
                response_deserializer=groundControl__pb2.cmdReply.FromString,
                _registered_method=True)
        self.getSerial = channel.unary_unary(
                '/ground_control/getSerial',
                request_serializer=groundControl__pb2.serialRequest.SerializeToString,
                response_deserializer=groundControl__pb2.serialReply.FromString,
                _registered_method=True)
        self.reportStatus = channel.unary_unary(
                '/ground_control/reportStatus',
                request_serializer=groundControl__pb2.status.SerializeToString,
                response_deserializer=groundControl__pb2.statusAck.FromString,
                _registered_method=True)
        self.sharePin = channel.unary_unary(
                '/ground_control/sharePin',
                request_serializer=groundControl__pb2.pinSend.SerializeToString,
                response_deserializer=groundControl__pb2.pinAck.FromString,
                _registered_method=True)


class ground_controlServicer(object):
    """Ground Control service for rovers
    """

    def getMap(self, request, context):
        """Sends requested map to rover
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCommands(self, request, context):
        """Sends command string with requested size to rover
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSerial(self, request, context):
        """Sends serial number for the mine at the given position to rover
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reportStatus(self, request, context):
        """Receives signal for when command execution is done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sharePin(self, request, context):
        """Gets a mine's PIN from the rover
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ground_controlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMap': grpc.unary_unary_rpc_method_handler(
                    servicer.getMap,
                    request_deserializer=groundControl__pb2.mapRequest.FromString,
                    response_serializer=groundControl__pb2.mapReply.SerializeToString,
            ),
            'getCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommands,
                    request_deserializer=groundControl__pb2.cmdReq.FromString,
                    response_serializer=groundControl__pb2.cmdReply.SerializeToString,
            ),
            'getSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.getSerial,
                    request_deserializer=groundControl__pb2.serialRequest.FromString,
                    response_serializer=groundControl__pb2.serialReply.SerializeToString,
            ),
            'reportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.reportStatus,
                    request_deserializer=groundControl__pb2.status.FromString,
                    response_serializer=groundControl__pb2.statusAck.SerializeToString,
            ),
            'sharePin': grpc.unary_unary_rpc_method_handler(
                    servicer.sharePin,
                    request_deserializer=groundControl__pb2.pinSend.FromString,
                    response_serializer=groundControl__pb2.pinAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ground_control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ground_control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ground_control(object):
    """Ground Control service for rovers
    """

    @staticmethod
    def getMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ground_control/getMap',
            groundControl__pb2.mapRequest.SerializeToString,
            groundControl__pb2.mapReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ground_control/getCommands',
            groundControl__pb2.cmdReq.SerializeToString,
            groundControl__pb2.cmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ground_control/getSerial',
            groundControl__pb2.serialRequest.SerializeToString,
            groundControl__pb2.serialReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ground_control/reportStatus',
            groundControl__pb2.status.SerializeToString,
            groundControl__pb2.statusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sharePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ground_control/sharePin',
            groundControl__pb2.pinSend.SerializeToString,
            groundControl__pb2.pinAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
